#!/usr/bin/env node
// Generates src/schema.ts (TypeScript types from schema.json) and
// src/index.ts (a CATALOGS map of every published version + CURRENT).
// Run via `pnpm --filter animation-catalog gen-types`. Output is committed and
// never hand-edited.

import { compile } from "json-schema-to-typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { listVersionFiles, pkgRoot, readCurrent, readSchema } from "./lib.mjs";

const srcDir = path.join(pkgRoot, "src");
mkdirSync(srcDir, { recursive: true });

const header = `// GENERATED by scripts/gen-types.mjs — do not edit by hand.\n`;

const schema = readSchema();
const types = await compile(schema, "Catalog", {
  bannerComment: header.trimEnd(),
  additionalProperties: false,
  style: { singleQuote: false, semi: true, printWidth: 110 },
});
writeFileSync(path.join(srcDir, "schema.ts"), types);

const files = listVersionFiles();
const current = readCurrent();

const imports = files
  .map(({ version }, i) => `import v${i} from "../versions/${version}.json" with { type: "json" };`)
  .join("\n");
const entries = files.map(({ version }, i) => `  "${version}": v${i} as unknown as Catalog,`).join("\n");

const index = `${header}import type { Catalog, CatalogEntry, CatalogParam } from "./schema.js";
${imports}

export type { Catalog, CatalogEntry, CatalogParam };
export type CatalogVersion = ${files.map((f) => `"${f.version}"`).join(" | ")};
export type Trigger = CatalogEntry["triggers"][number];
export type Category = CatalogEntry["category"];

/** Every published catalog version, keyed by semver. Immutable. */
export const CATALOGS: Readonly<Record<CatalogVersion, Catalog>> = {
${entries}
};

/** The version the editor, help page and mock agent author against. */
export const CURRENT_VERSION: CatalogVersion = "${current}";

export const CATALOG_VERSIONS: readonly CatalogVersion[] = [${files.map((f) => `"${f.version}"`).join(", ")}];

export function getCatalog(version: string): Catalog | undefined {
  return (CATALOGS as Record<string, Catalog>)[version];
}

export function getEntry(version: string, animationId: string): CatalogEntry | undefined {
  return getCatalog(version)?.entries.find((e) => e.id === animationId);
}

/** Keyframes name used in the runtime and in exports. Includes the catalog major version so
 *  assignments authored under different catalog versions never collide. */
export function keyframesName(animationId: string, version: string): string {
  return \`vm-\${animationId}-v\${version.split(".")[0]}\`;
}
`;
writeFileSync(path.join(srcDir, "index.ts"), index);

console.log(`gen-types: wrote src/schema.ts and src/index.ts (${files.length} version(s), current ${current})`);
