#!/usr/bin/env node
// Generates src/schema.ts (TypeScript types from schema.json) and
// src/index.ts (a CATALOGS map of every published version + CURRENT).
// Run via `pnpm --filter animation-catalog gen-types`. Output is committed and
// never hand-edited.

import { compile } from "json-schema-to-typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { listVersionFiles, pkgRoot, readCatalog, readCurrent, readSchema } from "./lib.mjs";

const srcDir = path.join(pkgRoot, "src");
mkdirSync(srcDir, { recursive: true });

const header = `// GENERATED by scripts/gen-types.mjs — do not edit by hand.\n`;

const schema = readSchema();
const types = await compile(schema, "Catalog", {
  bannerComment: header.trimEnd(),
  additionalProperties: false,
  style: { singleQuote: false, semi: true, printWidth: 110 },
});
writeFileSync(path.join(srcDir, "schema.ts"), types);

const files = listVersionFiles();
const current = readCurrent();

const imports = files
  .map(({ version }, i) => `import v${i} from "../versions/${version}.json" with { type: "json" };`)
  .join("\n");
const entries = files.map(({ version }, i) => `  "${version}": v${i} as unknown as Catalog,`).join("\n");

const index = `${header}import type { Catalog, CatalogEntry, CatalogParam } from "./schema.js";
${imports}

export type { Catalog, CatalogEntry, CatalogParam };
export type CatalogVersion = ${files.map((f) => `"${f.version}"`).join(" | ")};
export type Trigger = CatalogEntry["triggers"][number];
export type Category = CatalogEntry["category"];

/** Every published catalog version, keyed by semver. Immutable. */
export const CATALOGS: Readonly<Record<CatalogVersion, Catalog>> = {
${entries}
};

/** The version the editor, help page and mock agent author against. */
export const CURRENT_VERSION: CatalogVersion = "${current}";

export const CATALOG_VERSIONS: readonly CatalogVersion[] = [${files.map((f) => `"${f.version}"`).join(", ")}];

export function getCatalog(version: string): Catalog | undefined {
  return (CATALOGS as Record<string, Catalog>)[version];
}

export function getEntry(version: string, animationId: string): CatalogEntry | undefined {
  return getCatalog(version)?.entries.find((e) => e.id === animationId);
}

const SEMVER_RE = /^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$/;

/** Keyframes name used in the runtime and in exports. Named by the full (animationId,
 *  catalogVersion) pair — which is already the immutable identity of a keyframes template —
 *  so assignments authored under different catalog versions never collide, by construction. */
export function keyframesName(animationId: string, version: string): string {
  if (!SEMVER_RE.test(version)) {
    throw new Error(\`keyframesName: "\${version}" is not a strict MAJOR.MINOR.PATCH semver\`);
  }
  return \`vm-\${animationId}-v\${version.split(".").join("-")}\`;
}
`;
writeFileSync(path.join(srcDir, "index.ts"), index);

// manifest.json: a tiny, committed cross-language source of truth for the set of
// (version, animationId) pairs, so Kotlin and TS tests can assert they agree without
// either side importing the other's tooling. Ascending semver, ids in file order.
//
// keyframesNames additionally pins the expected keyframesName() output for every
// (version, id) pair, so the TS and Kotlin implementations of keyframesName() can each be
// proven to agree with this committed manifest without importing each other's code.
function keyframesNameForManifest(animationId, version) {
  return `vm-${animationId}-v${version.split(".").join("-")}`;
}

const manifest = {
  current,
  versions: Object.fromEntries(files.map(({ version, file }) => [version, readCatalog(file).entries.map((e) => e.id)])),
  keyframesNames: Object.fromEntries(
    files.map(({ version, file }) => [
      version,
      Object.fromEntries(
        readCatalog(file).entries.map((e) => [e.id, keyframesNameForManifest(e.id, version)]),
      ),
    ]),
  ),
};
writeFileSync(path.join(pkgRoot, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);

console.log(
  `gen-types: wrote src/schema.ts, src/index.ts and manifest.json (${files.length} version(s), current ${current})`,
);
