import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vibe Motion:
    "lib/api-client/schema.d.ts", // generated from apps/api/openapi.yaml
    "public/mockServiceWorker.js", // generated by `pnpm exec msw init public/ --save`
    // Playwright writes nothing here any more: e2e lives in apps/e2e (PR #11).
  ]),
]);

export default eslintConfig;
