// GENERATED by scripts/gen-types.mjs — do not edit by hand.
import type { Catalog, CatalogEntry, CatalogParam } from "./schema.js";
import v0 from "../versions/1.0.0.json" with { type: "json" };
import v1 from "../versions/1.1.0.json" with { type: "json" };

export type { Catalog, CatalogEntry, CatalogParam };
export type CatalogVersion = "1.0.0" | "1.1.0";
export type Trigger = CatalogEntry["triggers"][number];
export type Category = CatalogEntry["category"];

/** Every published catalog version, keyed by semver. Immutable. */
export const CATALOGS: Readonly<Record<CatalogVersion, Catalog>> = {
  "1.0.0": v0 as unknown as Catalog,
  "1.1.0": v1 as unknown as Catalog,
};

/** The version the editor, help page and mock agent author against. */
export const CURRENT_VERSION: CatalogVersion = "1.1.0";

export const CATALOG_VERSIONS: readonly CatalogVersion[] = ["1.0.0", "1.1.0"];

export function getCatalog(version: string): Catalog | undefined {
  return (CATALOGS as Record<string, Catalog>)[version];
}

export function getEntry(version: string, animationId: string): CatalogEntry | undefined {
  return getCatalog(version)?.entries.find((e) => e.id === animationId);
}

const SEMVER_RE = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;

/** Keyframes name used in the runtime and in exports. Named by the full (animationId,
 *  catalogVersion) pair — which is already the immutable identity of a keyframes template —
 *  so assignments authored under different catalog versions never collide, by construction. */
export function keyframesName(animationId: string, version: string): string {
  if (!SEMVER_RE.test(version)) {
    throw new Error(`keyframesName: "${version}" is not a strict MAJOR.MINOR.PATCH semver`);
  }
  return `vm-${animationId}-v${version.split(".").join("-")}`;
}
