// GENERATED by scripts/gen-types.mjs — do not edit by hand.
import type { Catalog, CatalogEntry, CatalogParam } from "./schema.js";
import v0 from "../versions/1.0.0.json" with { type: "json" };

export type { Catalog, CatalogEntry, CatalogParam };
export type CatalogVersion = "1.0.0";
export type Trigger = CatalogEntry["triggers"][number];
export type Category = CatalogEntry["category"];

/** Every published catalog version, keyed by semver. Immutable. */
export const CATALOGS: Readonly<Record<CatalogVersion, Catalog>> = {
  "1.0.0": v0 as unknown as Catalog,
};

/** The version the editor, help page and mock agent author against. */
export const CURRENT_VERSION: CatalogVersion = "1.0.0";

export const CATALOG_VERSIONS: readonly CatalogVersion[] = ["1.0.0"];

export function getCatalog(version: string): Catalog | undefined {
  return (CATALOGS as Record<string, Catalog>)[version];
}

export function getEntry(version: string, animationId: string): CatalogEntry | undefined {
  return getCatalog(version)?.entries.find((e) => e.id === animationId);
}

/** Keyframes name used in the runtime and in exports. Includes the catalog major version so
 *  assignments authored under different catalog versions never collide. */
export function keyframesName(animationId: string, version: string): string {
  return `vm-${animationId}-v${version.split(".")[0]}`;
}
