// GENERATED by scripts/gen-types.mjs — do not edit by hand.

export type CatalogParam = {
  [k: string]: unknown;
};

/**
 * Vibe Motion animation catalog. One published, immutable version of the CSS animation catalog. Files under versions/ must validate against this schema and are never edited once merged to main.
 */
export interface Catalog {
  /**
   * Semver of this catalog file. Must equal the file name without .json.
   */
  version: string;
  /**
   * @minItems 1
   */
  entries: [CatalogEntry, ...CatalogEntry[]];
}
export interface CatalogEntry {
  /**
   * Stable kebab-case identifier. Never reused for a different animation across versions.
   */
  id: string;
  name: string;
  category: "entrance" | "exit" | "attention" | "emphasis" | "continuous" | "hover";
  description: string;
  /**
   * Body of the @keyframes block only (the part inside the outer braces). The generator wraps it as `@keyframes vm-<id>-v<major> { ... }`. Reference animation-specific knobs as var(--vm-<key>).
   */
  keyframes: string;
  /**
   * Adjustable variables. The five standard keys (duration, delay, easing, iteration, direction) map to animation-* properties; any other key must declare cssVar and is set as a custom property on the element.
   */
  params: CatalogParam[];
  /**
   * @minItems 1
   */
  triggers: ["load" | "hover" | "in-view", ...("load" | "hover" | "in-view")[]];
  defaultTrigger?: "load" | "hover" | "in-view";
  /**
   * Optional declarations applied to the element whenever this animation is assigned, e.g. `transform-origin: center; backface-visibility: hidden;`.
   */
  baseStyles?: string;
}
