package dev.vibemotion.api.catalog

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
private data class CatalogManifest(
    val current: String,
    val versions: Map<String, List<String>>,
    val keyframesNames: Map<String, Map<String, String>>,
)

private val manifestJsonFormat = Json { ignoreUnknownKeys = true }

/**
 * Phase 1 exit criterion (docs/build_plan.md): "Kotlin and TS both load all versions and agree
 * on the set of (version, animationId) pairs."
 *
 * `manifest.json` is generated by `packages/animation-catalog/scripts/gen-types.mjs` from the
 * same published version files this build bundles via the `catalogResources` Gradle task
 * (see build.gradle.kts). This test proves [ClasspathCatalogRepository] agrees with it exactly,
 * so the JVM and TypeScript sides can never silently drift apart.
 */
class CatalogManifestTest :
    FunSpec({

        val manifestJson =
            checkNotNull(
                CatalogManifestTest::class.java.classLoader.getResourceAsStream("catalog/manifest.json"),
            ) { "Missing catalog/manifest.json on the classpath — is catalogResources wired to copy it?" }
                .bufferedReader()
                .use { it.readText() }
        val manifest = manifestJsonFormat.decodeFromString<CatalogManifest>(manifestJson)

        val repository = ClasspathCatalogRepository.load()

        test("currentVersion equals manifest.current") {
            repository.currentVersion shouldBe manifest.current
        }

        test("bundled versions equal the manifest's version set") {
            // Compares as sets, not lists: kotlinx.serialization does not guarantee that a
            // deserialized Map's key iteration order reflects the source JSON's key order.
            repository.versions().toSet() shouldBe manifest.versions.keys
        }

        test("bundled versions are ascending by semver, matching the manifest's keys sorted the same way") {
            repository.versions() shouldBe manifest.versions.keys.sortedWith(::compareSemver)
        }

        test("every version's animation ids equal the manifest's ids, in file order") {
            manifest.versions.forEach { (version, ids) ->
                val entries =
                    checkNotNull(repository.catalog(version)?.entries) {
                        "manifest lists version $version but the repository has no catalog for it"
                    }
                entries.map { it.id } shouldBe ids
            }
        }

        test("keyframesNames covers exactly the manifest's version set (not vacuously)") {
            // Without this, a manifest.json missing the keyframesNames key entirely (or empty)
            // would make the per-pair assertion below pass on zero pairs. Pin the key set first.
            manifest.keyframesNames.keys shouldBe manifest.versions.keys
        }

        test("every version's keyframesNames ids equal the manifest's ids (not vacuously)") {
            manifest.keyframesNames.forEach { (version, byId) ->
                byId.keys shouldBe manifest.versions[version]?.toSet()
            }
        }

        test("keyframesName() matches manifest.keyframesNames for every (version, id) pair") {
            manifest.keyframesNames.forEach { (version, byId) ->
                byId.forEach { (id, expected) ->
                    keyframesName(id, version) shouldBe expected
                }
            }
        }
    })
